import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/component/UserContext";
import Header from "@/component/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Document",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <Header />
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
